version: '3.3'

services:
  db:
    image: postgres
    volumes:
      - vpn4friends-account-db:/var/lib/postgresql/
    ports:
      - 5432:5432
  
  accounts_server:
    build: accounts_server
    volumes:
      - ./accounts_server:/code
    ports:
      - 8000:8000/tcp
    depends_on:
      - db
  
  openvpn_server:
    build: vpn_server
    volumes:
      - ./vpn_server/openvpn_data:/etc/openvpn
    ports:
      - 11451:1194
    cap_add:
      - NET_ADMIN


volumes:
  vpn4friends-account-db:
    driver: local
