version: '3.3'

services:
  db:
    image: postgres
    volumes:
      - vpn4friends-account-db:/var/lib/postgresql/
    ports:
      - 5432:5432
  
  accounts_server:
    build: accounts_server
    command: python manage.py makemigrations
    command: python manage.py migrate
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./accounts_server:/code
    ports:
      - 8000:8000
    depends_on:
      - db

volumes:
  vpn4friends-account-db:
    driver: local
