version: '3.3'

services:
  db:
    image: postgres
    volumes:
      - vpn4friends-account-db:/var/lib/postgresql/
    ports:
      - 5432:5432
  
  openvpn_server:
    build: vpn_server
    volumes:
      - ./vpn_server/openvpn_data:/etc/openvpn
      - ./vpn_server/accounts_server:/code
    ports:
      - 11451:1194
      - 80:8000
    cap_add:
      - NET_ADMIN
    depends_on:
      - db
    environment:
      - CA_PASS=default


volumes:
  vpn4friends-account-db:
    driver: local
