version: '3.3'

services:
  openvpn_server:
    build: vpn_server
    volumes:
      - ./vpn_server/openvpn_data:/etc/openvpn
      - ./vpn_server/accounts_server:/code
    ports:
      - 11451:1194  # OpenVPN
      - 80:8000  # WEB Front
    cap_add:
      - NET_ADMIN
    environment:
      - CA_PASS=default
      - EMAIL_TLS=True
      - EMAIL_HOST=smtp.examplecom
      - EMAIL_HOST_USER=user@example.com
      - EMAIL_HOST_PASSWORD=email_account_password
      - EMAIL_PORT=587
