version: '3.3'

services:
  db:
    image: postgres
    volumes:
      - vpn4friends-account-db:/var/lib/postgresql/
    ports:
      - 5432:5432
  
  accounts_server:
    build: accounts_server
    volumes:
      - ./accounts_server:/code
    ports:
      - 8000:8000/tcp
    depends_on:
      - db
  
  softether_server:
    build: vpn_server
    privileged: True
    tty: True
    ports:
      - 500:500/udp
      - 4500:4500/udp
      - 5555:5555
    volumes:
      - vpn4friends-vpn-data:/usr/vpnserver

volumes:
  vpn4friends-account-db:
    driver: local
  vpn4friends-vpn-data:
    driver: local
